### PR TITLE
Rework code

### PR DESCRIPTION
**Pull request by cli-ish**
This PR contains:

1. remove unused functions
2. solved all code guidelines flaws (via codechecker)
3. fixed restore error
4. added class autoloading
5. added amd module instead of dnd.js
6. added new grading method (difference)
7. added form filter for difference method
8. code simplified
9. unified coding structure. (removed iterator stuff and other complex structures not needed).

I would suggest that: `.github/workflows/moodle-plugin-ci.yml`

```
      #      - name: Moodle Code Checker
      #        if: ${{ always() }}
      #        run: moodle-plugin-ci codechecker --max-warnings 0
```

from now on runs on each commit to avoid diviation from the moodle coding style.

### CODE REVIEW

**Comment by ndunand** [comment]
Thanks for sharing! We're on the way to have a closer look at this.

@cli-ish could you share a bit about where all this work comes from? Was this part of a project, or of an update at your University? Also, did you use this reworked code in a production environment already?

Thanks again,
Nicolas

**Comment by ndunand** [comment]
Hi @CamilleTrd we should talk about this.

**Comment by ndunand** [comment]
Hi @cli-ish ,

Thanks for the clarification and explaining your usage context. I reiterate out thanks for sharing this. We'll look into this in the coming days and hopefully amend/approve the merge.

**Comment by yaakovopenapp** [comment]
Hello
We see a patch that works properly
It should be noted that in the version 4.1 model


Before the final submission of a partially answered question, an alert is displayed that the question was not answered
And you should change the alert to say that the question was partially answered

Screenshot from 2023-03-19 12-49-05

**Comment by ndunand** [comment]
Hello @cli-ish , I finally took the first steps to test this on our test Moodle 4.1.2 (Build: 20230313).

First problem, we can't create a new Matrix question for the following error and debug message display (truncated). The form displays afterwards but the items and answers table does not.

`QuickForm Error: nonexistent html element Element 'tagsheader' does not exist in HTML_QuickForm::getElement()
`

Screenshot 2023-03-22 at 11 21 41

**Comment by cli-ish** [comment]
@ndunand 

The Issue was that I used the function `$this->_form->getElement('tagsheader')` to fetch the Element and did not notice that it drops and error if the element is not present. I now use the `$this->_form->_elementIndex['tagsheader']` to ensure that this form has the tagsheader field. (This was always present at my end, since i tested with tags enabled).

We are also in the process to test the PR.

**Comment by cli-ish** [comment]
@yaakovopenapp This could potential relate to `question.php -> is_complete_response()` I will take a look into it.

**Comment by cli-ish** [comment]
@yaakovopenapp The commit [642f3ec](https://github.com/ndunand/moodle-qtype_matrix/pull/58/commits/642f3eca1938a05d02fcaad83e4ecc2e2cf9992c) should fix the issue you found. We now allow partial questions with all/difference method to be "complete" when atleast one row is answered.

**Comment by cli-ish** [comment]
@ndunand We have tested the PR and found no other bugs, so we can say from our side that it can be merged. Or is there something missing?

**Comment by relecand** [comment]
> Hello We see a patch that works properly It should be noted that in the version 4.1 model
> 
> Before the final submission of a partially answered question, an alert is displayed that the question was not answered And you should change the alert to say that the question was partially answered
> 
> Screenshot from 2023-03-19 12-49-05

It works in Moodle 3.9 until 4.1 (with at least PHP 7.4).

**Comment by NicoAlexH** [comment]
@cli-ish @relecand  We have tested the PR on our side as well, we found a small database upgrade issue but otherwise everything seems to be working fine. We're merging it and adding the tiny fix for the upgrade issue. Thank you very much for your work !

**Comment by ndunand** [comment]
@cli-ish thanks for sharing your contribution!

**Pull request merged**
